<?php
/**
 * @author Fran Mayers (https://merchantprotocol.com)
 * @copyright  Copyright (c) 2016 Merchant Protocol
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<div id="payment_form_mp_gateway_deposit" style="display:none">
	<h3><?php echo $this->getTitle() ?></h3>
	<p><?php echo $this->getDescription() ?></p>

    <ul class="form-list" id="payment_form_mp_gateway_deposit_fields">
        <li>
            <label for="mp_gateway_deposit_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
            <div class="input-box">
                <select id="mp_gateway_deposit_cc_type" name="deposit[cc_type]" class="required-entry validate-cc-type-select">
                    <option value=""><?php echo $this->__('--Please Select--')?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $types): ?>
                    <option value="<?php echo $types['value'] ?>"<?php if($types['value']==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $types['label'] ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </li>
        <li>
            <label for="mp_gateway_deposit_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
            <div class="input-box">
                <input type="text" id="mp_gateway_deposit_cc_number" name="deposit[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
            </div>
        </li>
        <li id="mp_gateway_deposit_cc_type_exp_div">
            <label for="mp_gateway_deposit_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="mp_gateway_deposit_expiration" name="deposit[cc_exp_month]" class="month validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="mp_gateway_deposit_expiration_yr" name="deposit[cc_exp_year]" class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <?php echo $this->getChildHtml() ?>
        <li id="mp_gateway_deposit_cc_type_cvv_div">
            <label for="mp_gateway_deposit_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="mp_gateway_deposit_cc_cid" name="deposit[cc_cid]" value="" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>

        <?php if ($this->hasSsCardType()): ?>
        <li id="mp_gateway_deposit_cc_type_ss_div">
            <ul class="inner-form">
                <li class="form-alt"><label for="mp_gateway_deposit_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
                <li>
                    <label for="mp_gateway_deposit_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                    <span class="input-box">
                        <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="mp_gateway_deposit_cc_issue" name="deposit[cc_ss_issue]" value="" />
                    </span>
                </li>

                <li>
                    <label for="mp_gateway_deposit_start_month"><?php echo $this->__('Start Date') ?>:</label>
                    <div class="input-box">
                        <div class="v-fix">
                            <select id="mp_gateway_deposit_start_month" name="deposit[cc_ss_start_month]" class="validate-cc-ukss month">
                            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                        <div class="v-fix">
                            <select id="mp_gateway_deposit_start_year" name="deposit[cc_ss_start_year]" class="validate-cc-ukss year">
                            <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </li>
                <li class="adv-container">&nbsp;</li>
            </ul>
            <script type="text/javascript">
            //<![CDATA[
//             var SSCheckedmp_gateway_deposit = function() {
//                 var elm = $('mp_gateway_deposit_cc_type');
//                 if (['SS','SM','SO'].indexOf(elm.value) != -1) {
//                     $('mp_gateway_deposit_cc_type_ss_div').show();
//                 } else {
//                     $('mp_gateway_deposit_cc_type_ss_div').hide();
//                 }
//             };

//             Event.observe($('mp_gateway_deposit_cc_type'), 'change', SSCheckedmp_gateway_deposit);
//             SSCheckedmp_gateway_deposit();
            //]]>
            </script>
        </li>
        <?php endif; ?>
    </ul>
</div>
<script type="text/javascript">
//<![CDATA[
    <?php foreach($this->getMethods() as $method): ?>
    $$("#p_method_<?php echo $method ?>").invoke('on', 'change', function() {
        $('payment_form_mp_gateway_deposit').show();
    });
    <?php endforeach ?>
    <?php foreach($this->getExcludedMethods() as $method): ?>
    $$("#p_method_<?php echo $method ?>").invoke('on', 'change', function() {
        $('payment_form_mp_gateway_deposit').hide();
    });
    <?php endforeach ?>
//]]>
</script>