<?php
/**
 * @author Fran Mayers (https://merchantprotocol.com)
 * @copyright  Copyright (c) 2016 Merchant Protocol
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php $_code = $this->getMethodCode() ?>
<?php $cards = $this->getSavedCards(); ?>
<?php $canSaveCards = $this->canSaveCard(); ?>
<?php $hasDefault = false; ?>

<div id="payment_form_<?php echo $_code ?>" style="display:none;">
<?php if ($canSaveCards): ?>
    <ul class="mpgateway-cards-list" id="mpgateway-cards-list">
    <?php foreach ($cards as $card): $isDefault = (bool)$card->getIsDefault(); ?>
        <li>
            <?php $checked = $isDefault ? ' checked="checked"': ''; ?>
            <?php if ($isDefault) $hasDefault = true; ?>

            <input type="radio" class="card-type" name="payment[cc_vault_id]"
                id="<?php echo $_code ?>-card-<?php echo $card->customer_vault_id; ?>" value="<?php echo $card->getCustomerVaultId(); ?>" <?php echo $checked; ?> />
            <label for="<?php echo $_code ?>-card-<?php echo $card->customer_vault_id; ?>">
                <?php echo $card->render(); ?>
            </label>
        </li>
    <?php endforeach; ?>
    <li>
        <?php $checked = !$hasDefault ? ' checked="checked"': ''; ?>
        <input type="radio" class="card-type" name="payment[cc_vault_id]"
            id="<?php echo $_code ?>-card-new" value="" <?php echo $checked; ?> />
        <label for="<?php echo $_code ?>-card-new">New Card</label>
<?php endif; ?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>_fields" <?php if ($hasDefault): ?> style="display:none;" <?php endif; ?>>
    <?php /*
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>" />
            </div>
        </li>
    */ ?>
        <li>
            <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                    <option value=""><?php echo $this->__('--Please Select--')?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
            <div class="input-box">
                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
            </div>
        </li>
        <li id="<?php echo $_code ?>_cc_type_exp_div">
            <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <?php echo $this->getChildHtml() ?>
        <?php if($this->hasVerification()): ?>
        <li id="<?php echo $_code ?>_cc_type_cvv_div">
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>
        <?php endif; ?>

        <?php if (!$this->forceSavedCards() && $this->canSaveCard()): ?>
            <li id="<?php echo $_code ?>_store_in_vault_div">
                <input type="checkbox" title="<?php echo $this->__('Save this card for future use') ?>"
                       class="input-checkbox" id="<?php echo $_code ?>_store_in_vault" name="payment[save_card]"
                       value="1"/>
                <label for="<?php echo $_code ?>_store_in_vault" style="float:none;"><?php echo $this->__('Save this card for future use') ?></label>
            </li>
        <?php endif; ?>

        <?php if ($this->hasSsCardType()): ?>
        <li id="<?php echo $_code ?>_cc_type_ss_div">
            <ul class="inner-form">
                <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
                <li>
                    <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                    <span class="input-box">
                        <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
                    </span>
                </li>

                <li>
                    <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
                    <div class="input-box">
                        <div class="v-fix">
                            <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                        <div class="v-fix">
                            <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                            <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </li>
                <li class="adv-container">&nbsp;</li>
            </ul>
            <script type="text/javascript">
            //<![CDATA[
            var SSChecked<?php echo $_code ?> = function() {
                var elm = $('<?php echo $_code ?>_cc_type');
                if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                    $('<?php echo $_code ?>_cc_type_ss_div').show();
                } else {
                    $('<?php echo $_code ?>_cc_type_ss_div').hide();
                }
            };

            Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
            SSChecked<?php echo $_code ?>();
            //]]>
            </script>
        </li>
        <?php endif; ?>
    </ul>
<?php if ($canSaveCards): ?>
    <?php /** Closing tag **/ ?>
    <li>
</ul>
<?php endif; ?>
</div>
<script type="text/javascript">
//<![CDATA[
    $$("[id^=<?php echo $_code ?>-card-]").invoke('on', 'change', function() {
        if (this.value != '') {
            $('payment_form_<?php echo $_code ?>_fields')
            $('payment_form_<?php echo $_code ?>_fields').hide();
            disableFormFields(document.getElementById('payment_form_<?php echo $_code ?>_fields'), true);
        } else {
            $('payment_form_<?php echo $_code ?>_fields').show();
            disableFormFields(document.getElementById('payment_form_<?php echo $_code ?>_fields'), false);
        }
    });

    function disableFormFields(container, isDisabled) {

        var tagNames = ["INPUT", "SELECT", "TEXTAREA", "CHECKBOX"];
        for (var i = 0; i < tagNames.length; i++) {
            var elems = container.getElementsByTagName(tagNames[i]);
            for (var j = 0; j < elems.length; j++) {
                elems[j].disabled = isDisabled;
            }
        }
    }
//]]>
</script>