<?php
/**
 * @author Fran Mayers (https://mageplugins.net)
 * @copyright  Copyright (c) 2016 Mage Plugins
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php $card = $this->getCard(); ?>

<img class="card-icon" src="<?php echo $card->getCardIcon() ?>" alt="<?php echo $card->getCardType() ?>" /> <?php echo $card->getCcTypeName() ?> 
<span class="card-number"><?php echo sprintf('xxxx-xxxx-xxxx-%s', $card->getLast4()); ?>,</span>
<span class="card-expiry"
	<span class="label"><?php echo $this->__('Exp.'); ?></span> <?php echo sprintf('%s/%s', sprintf('%02d', $card->getExpmon()), $card->getExpyear()); ?>
</span>