<?php

?>

<div class="sf-tabs">
    <div class="tab">
        <h3 class="tab-title">
            <?php echo $this->__('Rewrites'); ?>
        </h3>

        <div class="tab-content">
            
            <h3><?php echo $this->__('Module Rewrites'); ?></h3>
            <p class="help"><?php echo $this->__("This shows which plugins are trying to rewrite another module's class."); ?></p>
            
            <table>
                <thead>
                <tr>
                    <th><?php echo $this->__('Class'); ?></th>
                    <th><?php echo $this->__('Type'); ?></th>
                    <th><?php echo $this->__('Rewrites'); ?></th>
                    <th><?php echo $this->__('Conflict'); ?></th>
                </tr>
                </thead>
                <tbody>
                    <?php foreach (Mage::getModel('mp_debug/rewrites')->getRewritesCollection() as $item): ?>
                        <tr class="<?php if($item->getData('conflict')): ?>status-warning<?php endif; ?>">
                            <td><?php echo $this->escapeHtml($item['class']) ?></td>
                            <td style="white-space: nowrap;"><?php echo $this->escapeHtml($item['type']) ?></td>
                            <td>
                            	<?php foreach($item['rewrites']['classes'] as $rewrite): ?>
                            		<span style="color:<?php echo $rewrite['color'] ?>"><?php echo $rewrite['class'] ?></span><br/>
                            		<?php //echo $item['rewrites']['filter_condition'] ?>
                            	<?php endforeach ?>
                            </td>
                            <td><?php echo $this->escapeHtml($item['conflict']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="tab">
        <h3 class="tab-title">
            <?php echo $this->__('Incompatibility'); ?>
        </h3>

        <div class="tab-content">
            
            <h3><?php echo $this->__('Merchant Protocol Module Compatibility'); ?></h3>
            <p class="help"><?php echo $this->__("This page will show you which of our extensions are compatible with your store."); ?></p>
            
            <table>
                <thead>
                <tr>
                    <th><?php echo $this->__('Module'); ?></th>
                    <th><?php echo $this->__('Active'); ?></th>
                    <th><?php echo $this->__('Version'); ?></th>
                    <th><?php echo $this->__('Compatibility Issues'); ?></th>
                </tr>
                </thead>
                <tbody>
                    <?php foreach (Mage::getModel('mp_debug/compatibility')->getCollection() as $item): ?>
                        <tr class="<?php if($item->getData('conflict')): ?>status-warning<?php endif; ?>">
                            <td><?php echo $this->escapeHtml($item['class']) ?></td>
                            <td style="white-space: nowrap;"><?php echo $this->escapeHtml($item['active']) ?></td>
                            <td style="white-space: nowrap;"><?php echo $this->escapeHtml($item['version']) ?></td>
                            <td>
                            	<?php foreach($item['compatibility'] as $mod => $conflict): ?>
                            		<span style="color:<?php echo $conflict['color'] ?>"><?php echo $conflict['class'] ?></span><br/>
                            	<?php endforeach ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    
</div>