<?php

?>

<div class="sf-tabs">
    <div class="tab">
        <h3 class="tab-title">
            <?php echo $this->__('Dashboard'); ?>
        </h3>

        <div class="tab-content">
            
            <h3><?php echo $this->__('Merchant Protocol'); ?></h3>
            <p class="help"><?php echo $this->__("We are Magento Developers. We build awesome Magento plugins and provide Software Development Services."); ?></p>
            
        </div>
    </div>
    
</div>